Examen:
    type: entity
    table: examen
    indexes:
        codigo_examen:
            columns:
                - codigo_examen
    id:
        idExamen:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_examen
            generator:
                strategy: IDENTITY
    fields:
        codigoExamen:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: codigo_examen
        nombreExamen:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nombre_examen
        valorExamen:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: valor_examen
    lifecycleCallbacks: {  }
