Prevision:
    type: entity
    table: prevision
    id:
        idPrevision:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_prevision
        nombrePrevision:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            id: true
            column: nombre_prevision
    lifecycleCallbacks: {  }
