Rol:
    type: entity
    table: rol
    id:
        idRol:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_rol
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
