TomaExamen:
    type: entity
    table: toma_examen
    id:
        idToma:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_toma
        idAgenda:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_agenda
    fields:
        informeDelExamen:
            type: text
            nullable: false
            length: 16777215
            options:
                fixed: false
            column: informe_del_examen
        estado:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
                comment: '''Pendiente'',''Informado'''
    lifecycleCallbacks: {  }
