User:
    type: entity
    table: User
    indexes:
        id_rol:
            columns:
                - id_rol
    id:
        idUsuario:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_usuario
            generator:
                strategy: IDENTITY
    fields:
        nombreUsuario:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
            column: nombre_usuario
        clave:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        nombreCompleto:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nombre_completo
        idRol:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_rol
        estado:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
                comment: '''ACTIVO'',''INACTIVO'''
                default: ACTIVO
    lifecycleCallbacks: {  }
