Usuario:
    type: entity
    table: usuario
    indexes:
        id_rol:
            columns:
                - id_rol
    id:
        idUsuario:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_usuario
            generator:
                strategy: IDENTITY
    fields:
        usuario:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        clave:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        nombreUsuario:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nombre_usuario
        idRol:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_rol
    lifecycleCallbacks: {  }
